"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const Circle_1 = require("./Circle");
const Rectangle_1 = require("./Rectangle");
// let myShape = new Shape(10,15);
// console.log(myShape.getInfo());
let myCircle = new Circle_1.Circle(10, 4, 5);
console.log(myCircle.getInfo());
let myRecantange = new Rectangle_1.Rectangle(10, 6, 7, 7);
console.log(myRecantange.getInfo());
